[plugins.OAR3]
path = "/sys/fs/cgroup/"
poll_interval = "1s"

[plugins.aggregation]
interval = "1m"
function = "Sum"
metrics = []

[plugins.csv]
output_path = "alumet-output.csv"
force_flush = true
append_unit_to_metric_name = true
use_unit_display_name = true
csv_delimiter = ";"

[plugins.elasticsearch]
server_url = "http://localhost:9200"
allow_insecure = false
index_prefix = "alumet"
metric_unit_as_index_suffix = false

[plugins.elasticsearch.auth.basic]
user = "TODO"
password = "TODO"

[plugins.energy-attribution]
consumed_energy_metric_name = "rapl_consumed_energy"
hardware_usage_metric_name = "cpu_time_delta"

[plugins.energy-estimation-tdp]
poll_interval = "1s"
tdp = 100.0
nb_vcpu = 1.0
nb_cpu = 1.0
cpu_usage_per_pod = "cpu_time_delta"

[plugins.influxdb]
host = "http://localhost:8086"
token = "FILL ME"
org = "FILL ME"
bucket = "FILL ME"
attributes_as = "field"

[plugins.jetson]
poll_interval = "1s"
flush_interval = "5s"

[plugins.k8s]
path = "/sys/fs/cgroup/kubepods.slice/"
poll_interval = "1s"
kubernetes_api_url = "https://127.0.0.1:8080"
hostname = ""
token_retrieval = "kubectl"

[plugins.kwollect-input]
site=lyon
hostname=taurus-7

[plugins.mongodb]
host = "localhost"
port = "27017"
database = "FILL ME"
collection = "FILL ME"
username = "FILL ME"
password = "FILL ME"

[plugins.nvml]
poll_interval = "1s"
flush_interval = "5s"

[plugins.oar2-plugin]
path = "/sys/fs/cgroup"
poll_interval = "1s"

[plugins.opentelemetry]
collector_host = "http://localhost:4317"
prefix = ""
suffix = "_alumet"
append_unit_to_metric_name = true
use_unit_display_name = true
add_attributes_to_labels = true
push_interval_seconds = 15

[plugins.perf]
poll_interval = "1s"
flush_interval = "5s"
hardware_events = [
    "REF_CPU_CYCLES",
    "CACHE_MISSES",
    "BRANCH_MISSES",
]
software_events = []
cache_events = ["LL_READ_MISS"]

[plugins.procfs.kernel]
enabled = true
poll_interval = "5s"

[plugins.procfs.memory]
enabled = true
poll_interval = "5s"
metrics = [
    "MemTotal",
    "MemFree",
    "MemAvailable",
    "Cached",
    "SwapCached",
    "Active",
    "Inactive",
    "Mapped",
]

[plugins.procfs.processes]
enabled = true
refresh_interval = "2s"
strategy = "watcher"

[[plugins.procfs.processes.groups]]
exe_regex = ""
poll_interval = "2s"
flush_interval = "4s"

[plugins.procfs.processes.events]
poll_interval = "1s"
flush_interval = "4s"

[plugins.prometheus-exporter]
host = "0.0.0.0"
prefix = ""
suffix = "_alumet"
port = 9091
append_unit_to_metric_name = true
use_unit_display_name = true
add_attributes_to_labels = true

[plugins.rapl]
poll_interval = "1s"
flush_interval = "5s"
no_perf_events = false

[plugins.relay-client]
client_name = "MLPC"
relay_server = "[::1]:50051"
buffer_max_length = 4096
buffer_timeout = "30s"

[plugins.relay-client.retry]
max_times = 8
initial_delay = "500ms"
max_delay = "4s"

[plugins.relay-server]
address = "[::]:50051"

[plugins.socket-control]
socket_path = "alumet-control.sock"
