[package]
name = "plugin-kwollect-input"
version = "0.1.0"
edition = "2024"

[dependencies]
alumet = { version = "0.8.1", path = "../alumet" }
anyhow = "1.0.98"
chrono = "0.4.41"
hostname = "0.4.1"
log = "0.4.27"
serde = "1.0.219"
time = "0.3.41"

[lints]
workspace = true
